// BASE URL
export const BASE_URL = "https://pokeapi.co/api/v2/pokemon";

// FETCH POKEMON API
export const FETCH_POKEMON_REQUEST = "FETCH_POKEMON_REQUEST";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_ERROR = "FETCH_POKEMON_ERROR";
