// BASE URL
export const BASE_URL = "https://pokeapi.co/api/v2/pokemon";

// FETCH POKEMON API
export const FETCH_POKEMON_REQUEST = "FETCH_POKEMON_REQUEST";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_ERROR = "FETCH_POKEMON_ERROR";

// FAVORITE POKEMON
export const GET_FAVORITES_POKEMONS = "GET_FAVORITES_POKEMONS";
export const ADD_FAVORITE_POKEMON = "ADD_FAVORITE_POKEMON";
export const REMOVE_FAVORITE_POKEMON = "REMOVE_FAVORITE_POKEMON";
export const ERROR_FAVORITE_POKEMON = "ERROR_FAVORITE_POKEMON";
